### ISSUE TITLE
Polynomial format

### ISSUE THREAD

**Issue by daemontus** [coastalwhite/crc8-rs#1]
Hi! 

I have a (maybe stupid?) question about the polynomial used as an input for the CRC algorithm. What format is it in? I can't seem to find it anywhere in the documentation.

I have a CRC-8 system with a polynomial `x^8 + x^5 + x^4 + 1`. So for example, assuming a message `0b11011100` (0xDC), there should be a way to get the CRC checksum `0b01111001` (0x79). Using this [calculator](http://www.sunshine2k.de/coding/javascript/crc/crc_js.html), if I enter the input byte and specify the polynomial as 0x31 (`0b00110001` - wikipedia calls this MSB-first, so the `x^8` position is assumed, and the rest is explicitly written out), I get the expected result. 

However, with your library, I can't seem to get this result in any consistent way. I tried both [0xDC], [0xDC, 0], and [0, 0xDC] as inputs, as well as `0b00110001` and `0b10011000`, and their reversed variants in case its an issue with endianess. Finally, I decided to just brute-force the polynomial to get the expected result, and the polynomial I found was `0b10100101`, which doesn't make sense to me, as it does not correspond in any obvious way to `x^8 + x^5 + x^4 + 1`.

Could you please provide some explanation how the polynomial constant should be derived to match the broadly supported implementations?

Edit: Just to be clear, I have no problem believing that there is a version of CRC where this is correct. I'd just like to see the library documentation mention what version/parameters of CRC are actually used in the background.

**Comment by coastalwhite** [comment]
I saw this and I will add some extra examples and documentation by the end of the day.

**Comment by daemontus** [comment]
Cool, thank you! As a point of reference, this is the configuration I ended up using with the `crc` crate:

```
crc::Algorithm {
        poly: 0b00110001,
        init: 0x00,
        refin: false,
        refout: false,
        xorout: 0x00,
        check: 0x00,
        residue: 0x00,
}
```

**Comment by coastalwhite** [comment]
I think that is probably for the better. This crate was for a very specific use case I had. I did some testing, and it turns out that not everything is working as it is supposed to all the time. I am sorry for wasting your time for a bit. Closing this issue.
